@COPY /Y "MakeMesh\CPU\MakeMesh.exe" "..\MATLAB\"
@COPY /Y "MakeFace\CPU\MakeFace.exe" "..\MATLAB\"
@COPY /Y "MakeQuad\CPU\MakeQuad.exe" "..\MATLAB\"
@COPY /Y "Electrify\CPU\Electrify.exe" "..\MATLAB\"
@COPY /Y "MakeRHS\CPU\MakeRHS.exe" "..\MATLAB\"