function [ tetraMidPoint ] = GenerateTetraMidPoint( tetraCount, vertexList, tetraVertexIndex )
	
	tetraMidPoint = zeros( 3, tetraCount );
	
	for k = 1 : tetraCount
		tetraMidPoint( :, k ) = M.TetMid( ...
			vertexList( :, tetraVertexIndex( 1, k ) ), ...
			vertexList( :, tetraVertexIndex( 2, k ) ), ...
			vertexList( :, tetraVertexIndex( 3, k ) ), ...
			vertexList( :, tetraVertexIndex( 4, k ) ) ...
		);
	end
	
end