function SetIncwave( waveLength, dirX, dirY, dirZ, polX, polY, polZ )

    p = load( "..\Misc\pathList.mat" );
	incwavePath = p.dataFolder + "plane.incwave";
	
    fileId = fopen( incwavePath, 'w' );
    
    fprintf( fileId, [ 'Plane\n' ...
		'%12.12f\n' ...
		'%12.12f\n' ...
		'%12.12f\n' ...
		'%12.12f\n' ...
		'%12.12f\n' ...
		'%12.12f\n' ...
		'%12.12f\n' ...
		'%12.12f\n' ...
		'%12.12f\n' ...
		'%12.12f\n' ...
		'%12.12f\n' ...
		'%12.12f\n' ...
		'%12.12f\n' ...
		'%12.12f' ...
		], ...
		waveLength, ...
		dirX, ...
		dirY, ...
		dirZ, ...
		polX, ...
		polY, ...
		polZ, ...
		0, ...
		0, ...
		0, ...
		0, ...
		0, ...
		1, ...
		0 ...
	);
    
    fclose( fileId );
	
end
